# Generated by Django 4.2.2 on 2024-05-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_categories_delete_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='No Title')),
                ('description', models.TextField(default='No Description / (N/A)', null=True)),
                ('file_location', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(null=True)),
                ('similar_sample', models.TextField(null=True)),
                ('plagiarized', models.BooleanField(default=False)),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.research')),
            ],
        ),
    ]
