# Generated by Django 4.2.2 on 2024-05-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_research_file_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='file_location',
            field=models.FileField(upload_to='papers'),
        ),
    ]
