# Generated by Django 4.2.5 on 2024-05-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_research_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='No Title')),
                ('file_location', models.FileField(upload_to='reviewed_papers')),
                ('plagiarism_level', models.FloatField(default=0.0)),
                ('description', models.TextField(default=None)),
            ],
        ),
    ]
