# Generated by Django 4.2.5 on 2024-05-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_credibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credibility',
            name='description',
            field=models.TextField(default='No Description / (N/A)', null=True),
        ),
    ]
