# Generated by Django 4.2.5 on 2024-05-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_credibility_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='credibility',
            name='remarks',
            field=models.TextField(default=None),
        ),
    ]
