# Generated by Django 4.2.2 on 2024-05-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_credibility_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='credibility',
            name='is_plagirized',
            field=models.BooleanField(default=False),
        ),
    ]
